# Generated by Django 4.0 on 2022-03-19 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_addreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='addreport',
            name='approval',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='addreport',
            name='image',
            field=models.FileField(upload_to='images'),
        ),
    ]
