# Generated by Django 4.0 on 2022-03-23 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0005_addreport_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='rplogin',
            name='contact',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rplogin',
            name='firstname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rplogin',
            name='image_url',
            field=models.FileField(null=True, upload_to='images/users'),
        ),
        migrations.AddField(
            model_name='rplogin',
            name='lastname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rplogin',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rplogin',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rplogin',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
