# Generated by Django 4.0 on 2022-03-23 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0006_rplogin_contact_rplogin_firstname_rplogin_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rplogin',
            name='id_approve',
            field=models.BooleanField(null=True),
        ),
    ]
