# Generated by Django 4.0 on 2022-04-01 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0007_rplogin_id_approve'),
    ]

    operations = [
        migrations.AddField(
            model_name='rplogin',
            name='verified',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
