# Generated by Django 4.0 on 2022-04-01 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0008_rplogin_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='addreport',
            name='reporterid',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
